#服务器端口
server:
  port: 18202

#数据源配置
spring:
  #排除DruidDataSourceAutoConfigure
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为master
      primary: master
      datasource:
        master:
          url: ${idevelop.datasource.ipc.master.url}
          username: ${idevelop.datasource.ipc.master.username}
          password: ${idevelop.datasource.ipc.master.password}
#          url: jdbc:mysql://rm-wk47jx45tm6cu5958.mysql.rds.ops-devcloud.sd.sgcc.com.cn:14306/idevelop?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
#          username: xtjc
#          password: Xtjc@2023
        #          url: jdbc:mysql://127.0.0.1:3306/idevelop?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
        #          username: root
        #          password: 1234
        slave:
          url: ${idevelop.datasource.ipc.slave.url}
          username: ${idevelop.datasource.ipc.slave.username}
          password: ${idevelop.datasource.ipc.slave.password}
#          url: jdbc:mysql://25.41.32.179:3306/ent?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
#          username: ocn
#          password: Xtjc@2025
##          url: jdbc:mysql://127.0.0.1:3306/idevelop?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
##          username: root
##          password: 1234
