#服务器端口
server:
  port: 18202

#数据源配置
spring:
  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1
  #排除DruidDataSourceAutoConfigure
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为master
      primary: master
      datasource:
        master:
          url: ${idevelop.datasource.dev.url}
          username: ${idevelop.datasource.dev.username}
          password: ${idevelop.datasource.dev.password}
        slave:
          url: ${idevelop.datasource.demo.url}
          username: ${idevelop.datasource.demo.username}
          password: ${idevelop.datasource.demo.password}

