#服务器端口
server:
  port: 18100

#数据源配置
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${idevelop.datasource.dev.url}
#    username: ${idevelop.datasource.dev.username}
#    password: ${idevelop.datasource.dev.password}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/idevelop?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&socketTimeout=30000
    username: root
    password: wang123?
  autoconfigure:
    exclude:
      - com.lnsoft.core.swagger.SwaggerAutoConfiguration
#第三方登陆
social:
  enabled: true
  domain: http://127.0.0.1:1888


