#服务器端口
server:
  port: 18100

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${idevelop.datasource.dev.url}
    username: ${idevelop.datasource.dev.username}
    password: ${idevelop.datasource.dev.password}
  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1

#第三方登陆
social:
  enabled: true
  domain: http://127.0.0.1:1888


