#服务器端口
server:
  port: 8100

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${idevelop.datasource.prod.url}
    username: ${idevelop.datasource.prod.username}
    password: ${idevelop.datasource.prod.password}

#第三方登陆
social:
  enabled: true
  domain: http://127.0.0.1:1888


