#服务器端口
server:
  port: 18103

#数据源配置
#spring:
#  datasource:
#    url: ${idevelop.datasource.dev.url}
#    username: ${idevelop.datasource.dev.username}
#    password: ${idevelop.datasource.dev.password}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/idevelop?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&socketTimeout=30000
    username: root
    password: wang123?
  autoconfigure:
    exclude:
      - com.lnsoft.core.swagger.SwaggerAutoConfiguration