#服务器端口
server:
  port: 18103

#数据源配置
spring:
  datasource:
    url: ${idevelop.datasource.dev.url}
    username: ${idevelop.datasource.dev.username}
    password: ${idevelop.datasource.dev.password}
