#服务器端口
server:
  port: 8102

#数据源配置
spring:
  datasource:
    url: ${idevelop.datasource.prod.url}
    username: ${idevelop.datasource.prod.username}
    password: ${idevelop.datasource.prod.password}
