#数据源配置
server:
  port: 18103

spring:
  datasource:
    url: ${idevelop.datasource.prod.url}
    username: ${idevelop.datasource.prod.username}
    password: ${idevelop.datasource.prod.password}
