#数据源配置
server:
  port: 18103

spring:
  datasource:
    url: ${idevelop.datasource.test.url}
    username: ${idevelop.datasource.test.username}
    password: ${idevelop.datasource.test.password}
